//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

// {4391BDE2-44C5-4BDF-B4C5-BBEAE3CAF6E7}
DEFINE_GUID(CLSID_CSample,0x4391bde2, 0x44c5, 0x4bdf, 0xb4, 0xc5, 0xbb, 0xea, 0xe3, 0xca, 0xf6, 0xe7);
